import { createServer } from "node:http";

import { Effect, Schema } from "effect";

export interface TableRow {
  readonly ticker: string;
  readonly price: number;
  readonly hour: number;
  readonly day: number;
  readonly week: number;
}

export interface TableTruth {
  readonly seed: number;
  readonly visit: number;
  readonly rows: ReadonlyArray<TableRow>;
  readonly facts: Readonly<Record<string, string | number>>;
}

/** Values are already rounded to the displayed precision; visits change the highlighted ticker. */
export const tableTruth = (seed: number, visit: number): TableTruth => {
  const tickers = ["BTC", "ETH", "SOL", "AAPL"];
  const offset = Math.abs(seed % 4);

  const rows = tickers.map((ticker, index) => ({
    ticker,
    price: (12500 + ((Math.abs(seed) + index * 3711) % 25000)) / 100,
    hour: index === offset ? 18.75 : -(index + 1) / 4,
    day: index === (offset + 1) % 4 ? 9.25 : -((index + 1) * 137) / 100,
    week: index % 2 === 0 ? (731 + index * 123) / 100 : -(823 + index * 79) / 100,
  }));

  const highlight = rows[(offset + Math.abs(visit % 4)) % 4] ?? rows[0];
  const winner = rows.find((row) => row.day === 9.25);

  if (highlight === undefined || winner === undefined) throw new Error("Table rows missing");

  return {
    seed,
    visit,
    rows,
    facts: {
      ticker: highlight.ticker,
      dailyWinner: winner.ticker,
      dailyChange: winner.day,
      weekDirection: highlight.week >= 0 ? "up" : "down",
      weeklyChange: highlight.week,
    },
  };
};

const signed = (value: number) => `${value >= 0 ? "+" : ""}${value.toFixed(2)}%`;

export const tableMarkup = (truth: TableTruth) => `<!doctype html><meta charset="utf-8">
<title>Market table · visit ${truth.visit}</title>
<style>body{font:22px system-ui;background:#111827;color:#f3f4f6;margin:40px}h1{font-size:34px}table{border-collapse:collapse;width:100%}th,td{padding:18px;text-align:right;border-bottom:1px solid #475569}th:first-child,td:first-child{text-align:left}.highlight{background:#334155}.up{color:#6ee7b7}.down{color:#fca5a5}</style>
<h1>Market table</h1><p>Highlighted ticker: <strong>${truth.facts.ticker}</strong> · Visit ${truth.visit}</p>
<table><thead><tr><th>Ticker</th><th>Price</th><th>1h</th><th>24h</th><th>7d</th></tr></thead><tbody>
${truth.rows.map((row) => `<tr class="${row.ticker === truth.facts.ticker ? "highlight" : ""}"><td>${row.ticker}</td><td>$${row.price.toFixed(2)}</td>${[row.hour, row.day, row.week].map((value) => `<td class="${value >= 0 ? "up" : "down"}">${signed(value)}</td>`).join("")}</tr>`).join("")}
</tbody></table><p>Today means the 24h column; week means the 7d column.</p>`;

export class TableSiteError extends Schema.TaggedError<TableSiteError>()("TableSiteError", {
  cause: Schema.Unknown,
}) {}

export interface TableSite {
  readonly url: string;
  readonly visits: () => ReadonlyArray<TableTruth>;
  readonly close: () => Promise<void>;
}

/** Truth is generated by the host request ledger, independently of narration output. */
export const tableSite = (seed: number) =>
  Effect.acquireRelease(
    Effect.tryPromise({
      try: async (): Promise<TableSite> => {
        const visits: TableTruth[] = [];

        const server = createServer((request, response) => {
          if (new URL(request.url ?? "/", "http://table.test").pathname !== "/") {
            response.writeHead(404);
            response.end();

            return;
          }
          if (visits.length >= 100) {
            response.writeHead(429);
            response.end();

            return;
          }
          const truth = tableTruth(seed, visits.length);

          visits.push(truth);
          response.writeHead(200, {
            "content-type": "text/html; charset=utf-8",
            "cache-control": "no-store",
          });
          response.end(tableMarkup(truth));
        });

        await new Promise<void>((resolve, reject) => {
          server.once("error", reject);
          server.listen(0, "127.0.0.1", resolve);
        });
        const address = server.address();

        if (address === null || typeof address === "string") throw new Error("Table port missing");

        return {
          url: `http://127.0.0.1:${address.port}`,
          visits: () => [...visits],
          close: () =>
            new Promise<void>((resolve, reject) => {
              server.close((error) => (error === undefined ? resolve() : reject(error)));
              server.closeAllConnections();
            }),
        };
      },
      catch: (cause) => TableSiteError.make({ cause }),
    }),
    (site) => Effect.promise(site.close),
  );
